#!/usr/bin/env bash

mkdir $1
cd $1
cp ../../Makefile.template Makefile
sed -i "s/final_program/$1/" Makefile
mkdir src
cat << EOF > src/main.c
#include <stdio.h>

int
main(int argc, char **argv)
{
    printf("Hello, World!\n");
    return 0;
}
EOF
